# Configuration file for ALU_FACTORY
[ALU_FACTORY]
DB_URI = postgresql://alufactory:alufactory@localhost/alufactory
REDIS_URI = redis://:@127.0.0.1:6379
SECRET_KEY = b'{\xb3\xf1\xf2\xec\xec\xf9\x8a\xd8\xd1\x1d\xbf\x9f6.Y(\x1e\xdc}6\x8f\x1e}'
REDIS_PREFIX = alufactory
CRM_PORT = 8888
SIP_PORT = 9999
COMPANY_ID = alufactory

MEDIA_UPLOAD_FOLDER = /Users/babajan/Projects/alu-factory/backend/media/
APP_PATH = /Users/babajan/Projects/alu-factory/backend/app/

IMAGE_UPLOAD_MAX_SIZE_MB = 5
DOCUMENT_UPLOAD_MAX_SIZE_MB = 20
TEMPLATE_UPLOAD_MAX_SIZE_MB = 10
ANY_UPLOAD_MAX_SIZE_MB = 50

MEDIA_SERVE_URL = http://localhost:8000/media/
